{% set name = "ocetrac" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: ocetrac-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f8dd140581781fa0ed77bc462020e65afc9e544de0e203f937aa35857596b7c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - xarray
    - dask
    - scipy
    - scikit-image

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - ocetrac

about:
  home: https://github.com/ocetrac/ocetrac
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Label and track unique geospatial features from gridded datasets
  doc_url: https://ocetrac.readthedocs.io/

extra:
  recipe-maintainers:
    - hscannell
